docs: update vchart in treasures
NervJS/taro-docs pull request #196
Opened 2023-10-31 09:56 UTC by xile611

更新物料

VChart是一款开箱即用的多端图表库，由面向叙事的智能可视化解决方案VisActor出品，特点： 
* 一码多端： 自动适配桌面、H5、多个小程序环境 
* 场景沉淀： 面向最终用户沉淀可视化能力，解放开发者生产力 
* 面向叙事：综合应用标注、动画、流程控制叙事模板等一系列增强功能进行叙事可视化创作

github地址： https://github.com/VisActor/VChart
npm地址： https://www.npmjs.com/package/@visactor/taro-vchart
支持平台：

|        | 微信 | 阿里系 | 百度 | 头条 | H5  | RN  |
| :----: | :--: | :----: | :--: | :--: | :-: | :-: |
| 支持度 |  ✔️  |      |      |  ✔️    |     |     |

2023-11-01 02:31 UTC, ZakaryCode requested changes

2023-11-01 02:31 UTC, ZakaryCode commented on versioned_docs/version-3.x/treasures.md
> +### taro-vchart
可以在 docs/treasures.md 同步修改一下

2023-11-02 02:10 UTC, xile611 commented on versioned_docs/version-3.x/treasures.md
> +### taro-vchart
已经同步了 @ZakaryCode

2023-11-02 11:32 UTC, ZakaryCode approved these changes

2023-11-02 11:32 UTC, merged