docs: 插件文档更新完善
NervJS/taro-docs pull request #68
Opened 2023-02-13 07:41 UTC by tutuxxx

2023-02-14 02:39 UTC, ZakaryCode requested changes

2023-02-14 02:39 UTC, ZakaryCode commented on docs/platform-plugin/how.md
> +前置阅读：[【如何编写一个 Taro 插件】](./plugin-custom)。
此处路径错误

2023-02-14 02:57 UTC, tutuxxx commented on docs/platform-plugin/how.md
> +前置阅读：[【如何编写一个 Taro 插件】](./plugin-custom)。
plugin-custom是新增的路径，之所以新增是考虑到接下来新增运行时插件文档。新增后插件模块有三个子文章：如何使用、编写编译时插件、编写运行时插件。
另外，这个pr内容依赖taro cli的一个feat：https://github.com/NervJS/taro/pull/13283。

2023-03-24 12:05 UTC, ZakaryCode approved these changes

2023-03-24 12:05 UTC, merged